version: '3'

services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - todoapp-network
    environment:
      - ASPNETCORE_URLS=http://+:5000
    # depends_on:
    #   - sqlite

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "5173:5173"
    expose:
      - "5173"
    networks:
      - todoapp-network

  # sqlite:
  #   image: nouchka/sqlite3
  #   volumes:
  #     - ./backend/TodoApi/todoDev.db:/todoDev.db
  #   networks:
  #     - todoapp-network

networks:
  todoapp-network:
    driver: bridge
