version: '3'

services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - todoapp-network
    environment:
      - PORT=5000

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    networks:
      - todoapp-network

networks:
  todoapp-network:
    driver: bridge
