version: '3'

services:
  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      --host
    # environment:
    #   - ASPNETCORE_URLS=http://+:5000

  frontend:
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "5173:5173"
    networks:
      --host

networks:
  host:
    driver: bridge